baseurl = "http://konsulentkoppen.no"
title = "Konsulentkoppen"
author = "Kaffegutta"
copyright = ""
canonifyurls = true
paginate = 3
theme = "aglaus"

[params]
  disqusShortname = "l0lpalme" # optional
  toc = false # optional, When set to TRUE this parameter, table of contents appears in all articles.